import type {
  CoverageZoneTemplate,
  LiveBriefingResponse,
  SignalCategory,
  SourceHealth,
} from '../../src/types.js'

const signalSets: Array<readonly SignalCategory[]> = [
  ['storm', 'transport', 'public-safety'],
  ['flood', 'infrastructure', 'public-safety'],
  ['heat', 'airspace', 'transport'],
  ['air-quality', 'transport', 'infrastructure'],
]

function hashText(value: string) {
  let hash = 0

  for (const character of value) {
    hash = (hash * 31 + character.charCodeAt(0)) >>> 0
  }

  return hash
}

function isoMinutesAgo(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString()
}

function toTitleCase(value: string) {
  return value
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

function createWeather(zone: CoverageZoneTemplate) {
  const base = hashText(zone.id)
  const temperatureC = ((base % 15) + 6)
  const windKph = ((base % 35) + 12)
  const rainChance = (base % 55) + 35

  return {
    temperatureC,
    condition: rainChance > 70 ? 'Rain bands moving through the area' : 'Mixed cloud and local showers',
    windKph,
    rainChance,
    advisory: `Keep an eye on local conditions around ${zone.name}; this demo briefing is generated by the local API service.`,
  }
}

function createSources(zone: CoverageZoneTemplate): SourceHealth[] {
  return [
    {
      id: `${zone.id}-source-weather`,
      name: `${zone.name} weather mesh`,
      type: 'Weather',
      status: 'Healthy',
      lastSync: isoMinutesAgo(4),
      note: 'Radar and forecast layers are current.',
    },
    {
      id: `${zone.id}-source-civic`,
      name: `${zone.region} civic bulletin desk`,
      type: 'Civil',
      status: 'Healthy',
      lastSync: isoMinutesAgo(7),
      note: 'Public bulletins are publishing normally.',
    },
    {
      id: `${zone.id}-source-ops`,
      name: `${zone.country} operations exchange`,
      type: 'Infrastructure',
      status: 'Manual review',
      lastSync: isoMinutesAgo(12),
      note: 'Operational context is available but should be checked against authoritative local sources.',
    },
  ]
}

export function buildDemoBriefing(zone: CoverageZoneTemplate): LiveBriefingResponse {
  const setIndex = hashText(zone.id) % signalSets.length
  const [primaryCategory, secondaryCategory, tertiaryCategory] = signalSets[setIndex]
  const refreshedAt = new Date().toISOString()

  return {
    outlook: `${zone.name} is running on the local demo briefing service. Replace this endpoint with a real provider when you are ready to monitor live data.`,
    weather: createWeather(zone),
    signals: [
      {
        id: `${zone.id}-signal-primary`,
        title: `${toTitleCase(primaryCategory)} watch for ${zone.name}`,
        category: primaryCategory,
        severity: 'High',
        status: 'Live',
        issuedAt: isoMinutesAgo(18),
        source: `${zone.region} operations desk`,
        coverage: `${zone.name} coverage area`,
        summary: `Conditions in ${zone.name} need closer monitoring. This item is generated by the demo API to give the interface a realistic live state.`,
        hotspotLabel: zone.locationCodes[0] ?? zone.region,
        reactionCount: 6,
        tags: [zone.countryCode, toTitleCase(primaryCategory)],
      },
      {
        id: `${zone.id}-signal-secondary`,
        title: `${toTitleCase(secondaryCategory)} monitoring notice`,
        category: secondaryCategory,
        severity: 'Moderate',
        status: 'Monitoring',
        issuedAt: isoMinutesAgo(32),
        source: `${zone.country} coordination feed`,
        coverage: `${zone.region}`,
        summary: `This demo signal shows how secondary monitoring categories can sit alongside the main watch for ${zone.name}.`,
        hotspotLabel: zone.region,
        reactionCount: 3,
        tags: ['demo', toTitleCase(secondaryCategory)],
      },
      {
        id: `${zone.id}-signal-tertiary`,
        title: `${toTitleCase(tertiaryCategory)} recovery note`,
        category: tertiaryCategory,
        severity: 'Advisory',
        status: 'Recovery',
        issuedAt: isoMinutesAgo(58),
        source: `${zone.name} field bulletin`,
        coverage: `${zone.country}`,
        summary: `Use this demo entry to test low-severity or recovery-state rendering in the signal feed.`,
        hotspotLabel: zone.countryCode,
        reactionCount: 1,
        tags: ['recovery', 'demo'],
      },
    ],
    news: [
      {
        id: `${zone.id}-news-civic`,
        headline: `${zone.region} civic desk issues a local readiness reminder`,
        source: `${zone.region} civic desk`,
        publishedAt: isoMinutesAgo(14),
        summary: `Residents in ${zone.name} are being reminded to verify trusted sources and keep local response plans up to date.`,
        scope: 'Local',
      },
      {
        id: `${zone.id}-news-network`,
        headline: `${zone.country} network bulletin highlights multi-signal monitoring`,
        source: `${zone.country} network bulletin`,
        publishedAt: isoMinutesAgo(41),
        summary: 'This demo article exists so self-hosters can test the context bulletins panel without wiring a newsroom feed first.',
        scope: 'National',
      },
    ],
    sources: createSources(zone),
    actions: [
      {
        id: `${zone.id}-action-verify`,
        title: 'Verify local provider routing',
        description: 'Replace the demo endpoint with a real briefing service before relying on this zone operationally.',
        whenToUse: 'When finishing initial setup',
      },
      {
        id: `${zone.id}-action-review`,
        title: 'Review country and region coverage filters',
        description: 'Confirm the selected coverage area matches the codes and aliases your community will actually search.',
        whenToUse: 'Before sharing the deployment publicly',
      },
    ],
    refreshedAt,
    freshness: {
      status: 'live',
      checkedAt: refreshedAt,
      snapshotAgeMinutes: 0,
      message: 'Demo briefing refreshed from the local sample service.',
    },
  }
}
